language: R
cache: packages
r: release
repos:
  CRAN: https://cloud.r-project.org
warnings_are_errors: false

env:
  global:
  - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
addons:
  apt:
    packages:
    - r-base-dev
    - r-recommended
    - libxml2-dev
