version: '3.7'

services:

  proxy:
    image: jwilder/nginx-proxy:0.4.0
    container_name: jwilder-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro

  shiny:
    image: raquamaps/shiny:v0.1.7
    container_name: shiny
    environment:
      - VIRTUAL_HOST=birdrecoveries.nrm.se
      - VIRTUAL_PORT=3838
    #ports:
    #  - 3838:3838
