version: '3.7'

services:

  shiny:
    #image: raquamaps/shiny:v0.1.7
    image: inkimar/shiny:v0.1.4
    container_name: shiny
    environment:
      VIRTUAL_HOST: birdrecoveries-local.nrm.se
      VIRTUAL_PORT: 3838

networks:
  default:
    external:
       name: matomo_default
