#! make

stage-up:
	docker-compose -f docker-compose.stage.yml up -d 

stage-ps:
	docker-compose -f docker-compose.stage.yml ps

stage-logs:
	docker-compose -f docker-compose.stage.yml logs -f

stage-down:
	docker-compose -f docker-compose.stage.yml down --remove-orphans


# NOTE: if conflict then 'docker rm xyzxx'
