#! make

all-production-up:
	docker-compose -f docker-compose.prod.yml up -d

all-production-ps:
	docker-compose -f docker-compose.prod.yml ps

all-production-logs:
	docker-compose -f docker-compose.prod.yml logs -f

# if conflict then 'docker rm xyzxx'
