name: Build, Test, and Publish Shiny App

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]   # trigger docker publishing only on version tags
  pull_request:

jobs:
  build-r-package:
    name: Check R package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev libxml2-dev libcurl4-openssl-dev \
            libpng-dev libjpeg-dev libtiff-dev \
            libharfbuzz-dev libfribidi-dev

      - name: Setup R dependencies (with caching)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::remotes

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: --no-tests --no-manual --as-cran
          error-on: '"error"'
          check-dir: '"check"'

  docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    needs: build-r-package
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
